### ISSUE TITLE
Can't Edit MQTT Settings

### ISSUE THREAD

**Issue by spencercharest** [obiwan007/despresso#183]
**Describe the bug**
Once MQTT settings are saved I am not able to edit them. I can click the field and the input box will open but the backspace and delete keys do nothing. I'm only able to append text to the existing settings.

**To Reproduce**
1. Go to Settings -> Cloud and Network -> MQTT
2. Click a field like "username". If it does not have a value, add a value, save, and then click again to edit.
3. Attempt to modify the saved value. Text can only be appended, but not removed.

**Expected behavior**
MQTT fields should be editable

**Screenshots**

**Tablet (please complete the following information):**
 - Device: Samsung Galaxy Tab A7 Light
 - OS: Android 13
 - Version 13

**Additional context**
Attempted to force close and reopen app and restart tablet. Problem persists

**Comment by obiwan007** [comment]
Will be fixed in upcoming release

**Comment by spencercharest** [comment]
Awesome, thank you @obiwan007!

**Comment by obiwan007** [comment]
Is fixed in the latest release/beta.

**Comment by spencercharest** [comment]
Hey @obiwan007 I updated to the latest release this morning via the Play Store (167) and I'm still experiencing the same issue. I tried force quitting and also restarting my tablet but I still can't edit MQTT settings. Do you have any suggestions?

**Comment by obiwan007** [comment]
Can you provide a few more data? Which tablet? Which Android version etc.
It is working on my iPad and on my Galaxy Tab A8.
I can ust enter stuff in any of the settings text edit fields. Change the IP adress for example.
I only have an updated teclast (not with original OS) here. There it is working too. Maybe on the default very old Andoid OS 8 it is not working.

**Comment by spencercharest** [comment]
I'm using a Samsung Galaxy Tab A7 Light on Android 13. Let me try to do an OS update and I'll report back

**Comment by obiwan007** [comment]
If you have time pls record some screenvideo?
