### ISSUE TITLE
System UI stays active after keyboard was used

### ISSUE THREAD

**Issue by denschub** [obiwan007/despresso#74]
On my "K811C", which comes with a highly modern Android 8.1.0... when I use the keyboard, for example to type in the bean name, the system UI (the status icons on top, as well as the back/home/app-switcher buttons) stay active, overlaying part of the UI.

Using the app switcher to switch away and back to Despresso hides the UI again.

**Comment by obiwan007** [comment]
Probably a bug in Android or Flutter Keyboard handling. Not much we could do about it. Never seen it on any tablet before.

**Comment by obiwan007** [comment]
Maybe you could add some screenshots of it on acactly how to reproduce it?

**Comment by obiwan007** [comment]
Closing this as I hope it is now resolved.

**Comment by denschub** [comment]
This isn't fixed, I just didn't have the time to run a screen recording. Here is one:


https://user-images.githubusercontent.com/344777/236869010-c1655859-cf96-42e0-94c0-bbc618bfebd6.mp4

This is just me renaming a recipe. As soon as the keyboard shows up, you can see the app exiting fullscreen mode - the top notification bar is overlayed, and the system controls on the bottom are visible. This doesn't stop being there, until I use the app switcher to switch back to the app, at which point it goes back to fullscreen.

**Comment by obiwan007** [comment]
Sorry, I have no idea how to fix this. It seems to be an issue with the used Android system. Even the really old teclast is handling it well. I do not see the bottombar even if keyboard is visible. Maybe there is some setting on Android you can change?

**Comment by denschub** [comment]
I doubt this is a system-wide thing. While I don't know for sure, the behavior is fine in the de1app:

https://user-images.githubusercontent.com/344777/236877466-8764a897-0158-42ca-9b8e-a1daf0153f95.mp4

and this is exactly what I expect to happen. Quickly having a look at your sources, I noticed

https://github.com/obiwan007/despresso/blob/01ad9ee6514a7880d814a7b0f80ce901e2712ea1/lib/main.dart#L48

The [Flutter API documentation](https://api.flutter.dev/flutter/services/SystemChrome/setEnabledSystemUIMode.html) is actually fairly clear that what I'm seeing should be correct by default:

> The settings here can be overridden by the platform when System UI becomes necessary for functionality.
> 
> For example, on Android, when the keyboard becomes visible, it will enable the navigation bar and status bar system UI overlays. When the keyboard is closed, **Android will not restore the previous UI visibility settings((, and the UI visibility cannot be changed until 1 second after the keyboard is closed to prevent malware locking users from navigation buttons.
> 
> To regain "fullscreen" after text entry, the UI overlays can be set again after a delay of at least 1 second through [restoreSystemUIOverlays](https://api.flutter.dev/flutter/services/SystemChrome/restoreSystemUIOverlays.html) or calling this again. Otherwise, the original UI overlay settings will be automatically restored only when the application loses and regains focus.

I see no call to `restoreSystemUIOverlays` anywhere in your app, neither do I see another `setEnabledSystemUIMode` call. So what I'm seeing is most likely expected given the implementation. The same documentation (just another paragraph below) also mentions the [`SystemUiChangeCallback`](https://api.flutter.dev/flutter/services/SystemUiChangeCallback.html), which might be a good way to flip back to fullscreen after textinput. 

Alternatively, it might be a good idea to match the System UI flags to match [what de1app does](https://github.com/decentespresso/de1app/blob/5d84cd2fa215949a78ea09b639f260607dbcce23/de1plus/dui.tcl#L19-L27). Although this API appears to be deprecated, so that's fun.

Since you appear to be unable to reproduce, I'll poke at it when I have a bit more idle-time - but I'm currently busy with what feels like 30 different projects, so that might have to wait a bit, sorry.

**Comment by obiwan007** [comment]
You commented on setEnabledSystemUIMode ... so we are using this.. 
What we do not use is the invocation of this again and listening to some systemuichangecallback or handling the restoreSystemUIOverlays. I can not really test this without access to such hardware.
If I have time I will try to set up some test implementation.
The problem is that I actually have no clue when the keyboard is dismissed - issueing the 1s delay then is a bit tricky. All is solvable just a question of digging down.
Just strange that no other android tablet is having this kind of issues so far. Neither my Galaxy A8 nor the teclast. And nobody else complained so far - but this does not mean anything :)

Would be great to have other developers helping to figure out issues and actually solving them :)
Any help is welcome...

**Comment by denschub** [comment]
> The problem is that I actually have no clue when the keyboard is dismissed

It's probably good enough to do that whenever the input field looses focus.

**Comment by obiwan007** [comment]
Not so easy as we have many input fields. Handling this not on a global scale would need alot of changes all over the place...

**Comment by obiwan007** [comment]
Beta 13 contains a fix - maybe this is working for you...

**Comment by denschub** [comment]
Just tested beta 13 and it works great! Thank you.
